apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-boot-app-canary
  labels:
    app: my-spring-boot-app
    version: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-spring-boot-app
      version: canary
  template:
    metadata:
      labels:
        app: my-spring-boot-app
        version: canary
    spec:
      containers:
      - name: my-spring-boot-app
        image: jenkinsproject.azurecr.io/my-spring-boot-app:31
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"